server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 300
spring:
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /res/static/**
  thymeleaf:
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pchr?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 101MB
      location: d:\temp
      file-size-threshold: 10MB
  redis:
    password: 123456
    host: 192.168.50.128
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: -1
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bnt.hrms.entity
logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com.bnt.hrms: debug
